services:
  jade_db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    volumes:
      - jade_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jade_api:
    image: gleidsoncosta/jade-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - jade_db
    volumes:
      - storage:/app/storage
    restart: unless-stopped

volumes:
  jade_db:
  storage:


